train_data_path: "/home/a/dcase/tamamori/dev_data/slider/train"
test_data_path: "/home/a/dcase/tamamori/dev_data/slider/test"
model_directory: "/home/a/dcase/ito/diffusion/20241002/model"
result_directory: "/home/a/dcase/ito/diffusion/20241002/result"
batch_size: 128
epochs: 100
learning_rate: 0.001
n_fft: 1024
hop_length: 512
n_mels: 128
power: 2.0
